### ISSUE TITLE
[BUG] Status bar icon display error

### ISSUE THREAD

**Issue by ProudRabbit** [ArthurLobopro/easy-codesnap#13]
When I did not select the text, the code-snap icon displayed normally. But when I select some text, the code-snap icon disappears from the status bar. This is different from previous behavior.

- not select
![not select](https://github.com/ArthurLobopro/easy-codesnap/assets/56437960/e1505cf5-bc53-4fca-8fc1-3573a9daa40b)

- select
![select](https://github.com/ArthurLobopro/easy-codesnap/assets/56437960/292c5123-2f9a-4847-b54d-03bf3cb296cf)

**Comment by ArthurLobopro** [comment]
@ProudRabbit I am fixing this in this exactly moment, when I was refactoring the button controller I forget to revert the order of things.

 The fix release will be ready in some minutes

**Comment by ArthurLobopro** [comment]
@ProudRabbit the version 1.5.1 is available fixing this problem!
