### ISSUE TITLE
[Feature Request] Show Windows-style Window Controls 

### ISSUE THREAD

**Issue by pnvnd** [ArthurLobopro/easy-codesnap#22]
Easy CodeSnap is excellent for anyone who doesn't want to touch settings.  Thank you for creating this!

# Feature Request
Please add a setting to show Windows-style Window Controls.  Currently, the only option is to not show Window Controls.  When enabled, you only see the OS X style window buttons.  The Windows-style Window Controls should look like `_ ☐ x` on the top right instead of the red-yellow-green circles on the left.

Example:
<img width="105" alt="image" src="https://github.com/ArthurLobopro/easy-codesnap/assets/65086728/a1d0fe91-d685-41e5-9b4a-a482137e5acd">

**Comment by ArthurLobopro** [comment]
@pnvnd What do you think about that?

![image](https://github.com/ArthurLobopro/easy-codesnap/assets/64273139/b30db7c8-8f42-4e2e-b912-1bc32d287288)

**Comment by ArthurLobopro** [comment]
Maybe should I align the title on left like Windows?

**Comment by pnvnd** [comment]
Looks nice @ArthurLobopro! Aligning the title to the left like Windows would be great!  Would you also be able to make the title bar a different color?  Here's was my attempt: Instead of using `dot` I made a `square` like this:
```css
.square {
    width: 16px;
    height: 16px;
    margin-right: 8px;
}
```

![image](https://github.com/ArthurLobopro/easy-codesnap/assets/65086728/b95a5656-0ab5-4670-bf67-c3fa32d7d340)

Thank you for looking into this!

**Comment by ArthurLobopro** [comment]
I can  add a option to change the title bar background if you want, with the transparent value as default

**Comment by ArthurLobopro** [comment]
@pnvnd I think change the title bar background isn't a good idea because of this:

![image](https://github.com/ArthurLobopro/easy-codesnap/assets/64273139/156bff57-98a3-4d35-b5ac-fea5d8a5caff)

The title bar don't fill all top container, so if I change its background it will looks strange

**Comment by pnvnd** [comment]
No worries, it's fine.  Thank you for checking this out.  The Windows-style icons is more than enough for me 😄

**Comment by ArthurLobopro** [comment]
@pnvnd it's done! In some minutes the version 1.8.0 will be available for download
