### ISSUE TITLE
What exactly does the `Link on editor` switch do?

### ISSUE THREAD

**Issue by AAABingBing** [ArthurLobopro/easy-codesnap#48]
What exactly does the `Link on editor` switch do?

I tried turning this switch on and nothing seemed to change.

**Comment by ArthurLobopro** [comment]
@AAABingBing, the `Lock Changes` feature ignore all selection changes from any editors. The `Link on Editor` will do the same thing, but keeps watching the changes from the current selection editor. With current selection I refer to the selection showed in the Snap Screen.

**Comment by ArthurLobopro** [comment]
Here is a video sample


https://github.com/ArthurLobopro/easy-codesnap/assets/64273139/d0bf6f88-cdc4-4306-89c9-0277c9477bfd

**Comment by AAABingBing** [comment]
> Here is a video sample
> 
>  untitled.mp4

Thank you for your reply
Easy CodeSnap is the best screenshot extension I have ever used
I will recommend it to people around me

**Comment by ArthurLobopro** [comment]
@AAABingBing Thank you! I will be very grateful if you could leave a review on marketplace.

**Comment by AAABingBing** [comment]
> @AAABingBing Thank you! I will be very grateful if you could leave a review on marketplace.

Yes, I will definitely.
