### ISSUE TITLE
[Feature Request] It is recommended to add multi-segment selection support

### ISSUE THREAD

**Issue by AAABingBing** [ArthurLobopro/easy-codesnap#49]
Like this:

![image](https://github.com/ArthurLobopro/easy-codesnap/assets/53040248/fa58c640-bb1f-4eb1-b6e6-5db892bf044b)

**Comment by ArthurLobopro** [comment]
@AAABingBing This can generate a lot of bugs hard to fix. Using two selections, the feature to fast refresh will not work correctly. The extension watches your current selection to update the snap screen, with two or more selections it will break. Sorry, but it's not possible for te moment

**Comment by AAABingBing** [comment]
> @AAABingBing This can generate a lot of bugs hard to fix. Using two selections, the feature to fast refresh will not work correctly. The extension watches your current selection to update the snap screen, with two or more selections it will break. Sorry, but it's not possible for te moment

I can understand
Indeed, there are not many such usage scenarios
