### ISSUE TITLE
Line number cannot be highlighted

### ISSUE THREAD

**Issue by AAABingBing** [ArthurLobopro/easy-codesnap#50]
When I click to modify the row style, the row numbers are not highlighted like in [Codesnap Plus](https://github.com/eugenejeonme/CodeSnap-plus-fix)

Is it possible to add a line number highlighting effect similar to mouse hovering to the rows with style, just like the mouse hovering on the fifth row?

![image](https://github.com/ArthurLobopro/easy-codesnap/assets/53040248/e6c673b8-c118-4cff-8ab2-612dc0d5ecb1)

**Comment by ArthurLobopro** [comment]
I think I will add an option to enable or disable line number highlight, so we can have both behaviors

**Comment by ArthurLobopro** [comment]
![image](https://github.com/ArthurLobopro/easy-codesnap/assets/64273139/01e79fb9-8af1-4b8e-a565-061d51f422f2)

CodeSnap Plus has some bugs like this, I unhighlighted the line and the hover effect persists. I need to think how to update hover effect to work with hightlight too

**Comment by AAABingBing** [comment]
> ![image](https://private-user-images.githubusercontent.com/64273139/343793539-01e79fb9-8af1-4b8e-a565-061d51f422f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1MzYwMDEsIm5iZiI6MTcxOTUzNTcwMSwicGF0aCI6Ii82NDI3MzEzOS8zNDM3OTM1MzktMDFlNzlmYjktOGFmMS00YjhlLWE1NjUtMDYxZDUxZjQyMmYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDAwNDgyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTdlNmMwNmU5MWU5YzQ1N2RmN2Y1OGJjZWE2NGMxYjRlN2YzZjE0NjViMmNjYTkzYmJlNmNiOTgwMzE4MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UueyOWRBIGd5AOGveDKYWmUG28oitjitJLFaL5XIwXY)
> 
> CodeSnap Plus has some bugs like this, I unhighlighted the line and the hover effect persists. I need to think how to update hover effect to work with hightlight too

Yes, I also encountered this problem while using CodeSnap Plus

**Comment by AAABingBing** [comment]
> In some minutes, the version 1.15 will be available fixing this. I added a new option to highlight the line number, it's `false` by default to keep the default behavior, but it can be activated easily by one time config menu!

Problem solved perfectly
Thank you for your efforts
`Easy CodeSnap` is the best screenshot extension I have ever used
