### ISSUE TITLE
[Feature Request] It is recommended to add a configuration item that hides `padding`

### ISSUE THREAD

**Issue by AAABingBing** [ArthurLobopro/easy-codesnap#55]
It is recommended to add a configuration item that hides `padding`

![image](https://github.com/user-attachments/assets/e7915e03-3d7e-4ef2-88aa-cf921240363a)

**Comment by ArthurLobopro** [comment]
@AAABingBing this config exists, there are 2 ways to hide it.

## Changing target to window

![image](https://github.com/user-attachments/assets/66032771-60ad-4b2d-af47-5096ec1b01e6)

## Or opening extension settings and setting Container Padding to 0

![image](https://github.com/user-attachments/assets/9ef64233-855f-4a8f-baf9-ccdcf80b294a)

**Comment by AAABingBing** [comment]
> @AAABingBing this config exists, there are 2 ways to hide it.
> 
> ## Changing target to window
> ![image](https://private-user-images.githubusercontent.com/64273139/349956836-66032771-60ad-4b2d-af47-5096ec1b01e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY4MTIsIm5iZiI6MTcyMTMwNjUxMiwicGF0aCI6Ii82NDI3MzEzOS8zNDk5NTY4MzYtNjYwMzI3NzEtNjBhZC00YjJkLWFmNDctNTA5NmVjMWIwMWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBhZGYwMmE5NzFkNzFjMjYwNzY3NGYyYjM4ZjdjNmYwMDIzOGFlNTVlYzIwNDRkODZjZTQ1YTVmZWExZTg0YmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CdUWZtVhub84njGHy6teBuJdseR8Sy5b3s-t76UtSyo)
> 
> ## Or opening extension settings and setting Container Padding to 0
> ![image](https://private-user-images.githubusercontent.com/64273139/349957407-9ef64233-855f-4a8f-baf9-ccdcf80b294a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMDY4MTIsIm5iZiI6MTcyMTMwNjUxMiwicGF0aCI6Ii82NDI3MzEzOS8zNDk5NTc0MDctOWVmNjQyMzMtODU1Zi00YThmLWJhZjktY2NkY2Y4MGIyOTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE4VDEyNDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlOTRkYzA3YTM5NzIzNWIxZDc1MTNkMGY1ZTYxNTY0MzA3MmUyZjc1ZDA2NGFmZDdjOTU3MDM2YzVjMTJjNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KCxBeB2-V0xxcDezK7YTVdGqdpp_i0k7-H61WafHGow)

Thanks for your reply

**Comment by ArthurLobopro** [comment]
@AAABingBing 

Note: Changing target to window will only hide padding from snap, but you can see the padding in the Snap Screen.

The config bar is only for quick settings, to change advanced settings you need to open settings and change manually, you can change the background from container too using another colors or gradientes like this:

![image](https://github.com/user-attachments/assets/168918c2-33c0-4a82-a52d-b1cef4c22abf)
![image](https://github.com/user-attachments/assets/2f6aed2c-5678-4dc3-a888-3e0ea972a4e5)
