### ISSUE TITLE
Add requests for multiple Chinese languages

### ISSUE THREAD

**Issue by Web-Coke** [ArthurLobopro/easy-codesnap#60]
This is the best code snapshot plugin in VS Code, the fly in the ointment is that it only supports English, can other languages such as Chinese be added?

**Comment by ArthurLobopro** [comment]
@Web-Coke I was thinking how to add languages support for a long time. I am Brasilian and I barely speak English, when I add support to languages I will need help to add another languages. So if you could add Chinese it will be great

**Comment by ArthurLobopro** [comment]
@Web-Coke do you know any open source extension that supports multiple languages? If I could take a look on its source it may help to translate Easy CodeSnap

**Comment by ArthurLobopro** [comment]
@Web-Coke hey I added a structure to add new idiom packages but I can't speak Chinese so I am not abe to add Chinese idiom packages. Fell free to add it yourself or ask a friend to do It!

**Comment by ArthurLobopro** [comment]
@Web-Coke No Problem, Chinese support was added by @CoffeeChaton recently. If you like it, please tell your friends about my extension!
