### ISSUE TITLE
Specific code cannot generate screenshots

### ISSUE THREAD

**Issue by WX-Yang** [ArthurLobopro/easy-codesnap#64]
`ALOGE("%s wrong audio hw device version %04x", __func__, (*dev)->common.version);`

This code cannot generate screenshots, changing `%04x` to `%x` will work, All versions of CodeSnap have this problem.

**Comment by ArthurLobopro** [comment]
@WX-Yang saving as svg works, so It may be an error with PNG format. I will take a look later but I have no idea why It happens

**Comment by ArthurLobopro** [comment]
![image](https://github.com/user-attachments/assets/45dadee1-23c8-4294-8443-60e552ec9c41)

I put these logs to find where the error is happening and there is the result.

![image](https://github.com/user-attachments/assets/fb32dedc-39a8-4e26-809d-80a32937b8bf)

The error happens during domtoimage execution. All CodeSnaps uses this lib to capture png files

**Comment by ArthurLobopro** [comment]
@WX-Yang I added a fallback to domtoimage, so I think this bug will not happen again. If after this version you see this error again or other error please tell me
