### ISSUE TITLE
[Feature Request] Follows `editor.fontLigatures` setting

### ISSUE THREAD

**Issue by DarkRRb** [ArthurLobopro/easy-codesnap#71]
![image](https://github.com/user-attachments/assets/2a72a8d4-5967-4fc2-b9ae-13f43e4d1e7a)

**Comment by ArthurLobopro** [comment]
Hello, this feature should exist in CodeSnap. If this isn't working, a VSCode update may have broken it. I don't know how exactly font ligatures works with CSS. I will take a look and try to fix it

**Comment by ArthurLobopro** [comment]
I did a test with these configs and it's working

```json
//settings.json
{
    "editor.fontFamily": "'Cascadia Code'",
    "editor.fontLigatures": true
}
```

![image](https://github.com/user-attachments/assets/e1d0547a-a5ef-4cdc-986b-f870b5800bec)

Please check if you have the desired font with support for font ligatures installed on your device.

If the error persists, please reopen this issue with more details like font-family, current Easy CodeSnap config, vscode version, etc...

**Comment by DarkRRb** [comment]
After testing, we found that the Esay CodeSnap window that is already open will not detect the config update, just reopen it.

thx.

**Comment by ArthurLobopro** [comment]
Sometimes you just need to Reset Settings. This button will require the extension and editor settings again and update the Snap Screen

![image](https://github.com/user-attachments/assets/aaf936c0-cece-4ece-9939-fb662c5492d7)
