### ISSUE TITLE
Does not highlight

### ISSUE THREAD

**Issue by ProudRabbit** [ArthurLobopro/easy-codesnap#78]
When I use Codesnap , there is no syntax highlighting.

![image](https://github.com/user-attachments/assets/35a9d8e9-3f2c-4305-854f-912db8085a4c)

**Comment by ArthurLobopro** [comment]
@ProudRabbit can you verify if this happen in other codes with other languages?

**Comment by ProudRabbit** [comment]
@ArthurLobopro I've tested both C and Python, and neither has syntax highlighting.

**Comment by ArthurLobopro** [comment]
@ProudRabbit I tested in python and the extension is working correctly for me. The syntax highlight is made copying the styled text from vscode editor using "editor.action.clipboardCopyWithSyntaxHighlightingAction". This command copy the text as HTML with all syntax highlight.  It looks like your vscode is not doing this command well.

**Comment by ArthurLobopro** [comment]
@ProudRabbit if you have a google account you can made a simple test:

![image](https://github.com/user-attachments/assets/1294b49e-48a0-4924-8316-30c7d3841cb2)
You can select a code and use Ctrl + Shift + P and use the command `Copy With Syntax Highlight`

So you can create a Google Docs document and paste te code there.

![image](https://github.com/user-attachments/assets/8d5b8e49-ad6f-4020-9e11-b94011d97694)

Here is the code pasted in my google docs. If you made this you can test if the vscode command is working well.

**Comment by ProudRabbit** [comment]
@ArthurLobopro I re-installed vscode and tested it. When I did not log in to the account to sync settings, I copied the code to word. The syntax highlight was still there. After I logged in to the account, the syntax highlight was gone. Disable all extensions and the problem persists.   "editor : copy with syntax highlighting" always on.

**Comment by ArthurLobopro** [comment]
@ProudRabbit it look like some VSCode setting you have sync is breaking the Highlight. Are you using experimental GPU rendering. I saw something a VSCode project to render the code using a canvas to use the GPU. If you are using this feature, maybe the text will not be stylized when you copy

**Comment by ProudRabbit** [comment]
@ArthurLobopro I have found the reason. The issue is caused by the setting `editor.experimentalEditContextEnabled:true` . Thank you for your help. 😄  👍

**Comment by ArthurLobopro** [comment]
@ProudRabbit nice! If you have any problems don't hesitate to open a issue to solve the problem!
