### ISSUE TITLE
Add the function of highlighting line numbers.

### ISSUE THREAD

**Issue by ProudRabbit** [ArthurLobopro/easy-codesnap#8]
Can add the same line number highlighting feature as the [CodeSnap-plus](https://github.com/eugenejeonme/CodeSnap-plus-fix) extension?

example:
![](https://raw.githubusercontent.com/eugenejeonme/CodeSnap-plus-fix/main/examples/ui.png)

**Comment by ArthurLobopro** [comment]
@ProudRabbit yes I can, but awnser me a question. It's normal in CodeSnap plus you lose the highlight after change the selection right?

**Comment by ProudRabbit** [comment]
@ArthurLobopro yeap.

**Comment by ArthurLobopro** [comment]
@ProudRabbit I added first a feature to lock the snap instances to create a secure edition ambient to highlight the lines without loses possibilities

**Comment by ProudRabbit** [comment]
@ArthurLobopro wow, you are very nice.

**Comment by ArthurLobopro** [comment]
@ProudRabbit thank you! The new version is here with lock function, I will add the highlight this week if I have the necessary time

**Comment by ArthurLobopro** [comment]
@ProudRabbit feature successfully added, please notify me if you had any problems with that. If you like this extension, please recommend to programmer friends and gave 5 stars, It will help me so much!
